### ISSUE TITLE
Second Panel

### ISSUE THREAD

**Issue by thanasisloi7** [maisken/Paradox_IP150#16]
Hello, can i add a second panel (second ip150 module) ?

**Comment by alfredopironti** [comment]
Hi,

Yes you can add a second panel by installing another instance of this add-on (you may need to create a local copy if hassio doesn't allow the same add-on to be installed twice).

Configure the second add-on to connect to the second IP150 module (and, likely, the same MQTT broker). Make sure to configure different MQTT topics, so that you can distinguish between the state of the two modules form MQTT.

In the HA config, you can then define a second panel that connects to the second set of MQTT topics.

Does this explain?

**Comment by thanasisloi7** [comment]
It works, 
thank for your help!

**Comment by alfredopironti** [comment]
Hi,

Glad to see it works! Just for future reference, did you manage to install a second instance of the add-on, or did you need to create a local copy?

**Comment by thanasisloi7** [comment]
You need to create a local copy
hassio/addons/local/Paradox_IP150

**Comment by alfredopironti** [comment]
Thanks for circling back, that's what I expected. Closing this now.
